### ISSUE TITLE
weopen-developer\WeMini\User.php文件问题

### ISSUE THREAD

**Issue by chenjiajing** [zoujingli/WeOpenDeveloper#5]
weopen-developer\WeMini\User.php 
get()方法
`public function get($appid)
    {
        $url = "https://api.weixin.qq.com/cgi-bin/open/unbind?access_token=ACCESS_TOKEN";
        $this->registerApi($url, __FUNCTION__, func_get_args());
        return $this->httpPostForJson($url, ['appid' => $appid]);
    }`
url 接口是不是错了，应该是 https://api.weixin.qq.com/cgi-bin/open/get?access_token=xxxx，这里写成了unbind @zoujingli

**Comment by zoujingli** [comment]
感谢反馈，已经处理
